name: tsrnasearch_env
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.0
  - alsa-lib=1.1.5
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - bz2file=0.98
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2019.11.28
  - click=7.1.2
  - curl=7.64.0
  - cutadapt=1.18
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.13.1
  - freetype=2.10.2
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - ghostscript=9.22
  - giflib=5.2.1
  - glib=2.65.0
  - graphite2=1.3.13
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.4.0
  - htslib=1.9
  - icu=67.1
  - jinja2=2.11.2
  - jpeg=9d
  - krb5=1.16.3
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.0
  - libdeflate=1.2
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - libgit2=0.27.8
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.0
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - make=4.3
  - markupsafe=1.1.1
  - mro-base=3.5.1
  - mro-base_impl=3.5.1
  - mro-basics=3.5.1
  - ncurses=6.1
  - numpy=1.15.4
  - openjdk=11.0.1
  - openssl=1.0.2u
  - pandoc=2.10
  - pango=1.42.4
  - pcre=8.44
  - perl=5.26.2
  - pigz=2.3.4
  - pip=20.1.1
  - pixman=0.38.0
  - pthread-stubs=0.4
  - python=2.7.15
  - python_abi=2.7
  - pyyaml=5.3.1
  - r=3.5.1
  - r-boot=1.3_20
  - r-checkpoint=0.4.4
  - r-class=7.3_14
  - r-cluster=2.0.7_1
  - r-codetools=0.2_15
  - r-curl=3.2
  - r-deployrrserve=9.0.0
  - r-doparallel=1.0.13
  - r-foreach=1.5.0
  - r-foreign=0.8_70
  - r-iterators=1.0.10
  - r-jsonlite=1.5
  - r-kernsmooth=2.23_15
  - r-lattice=0.20_35
  - r-mass=7.3_49
  - r-matrix=1.2_14
  - r-mgcv=1.8_23
  - r-microsoftr=3.5.0.108
  - r-nlme=3.1_137
  - r-nnet=7.3_12
  - r-png=0.1_7
  - r-r6=2.2.2
  - r-recommended=3.5.1
  - r-revoioq=10.0.0
  - r-revomods=11.0.0
  - r-revoutils=11.0.0
  - r-revoutilsmath=11.0.0
  - r-rpart=4.1_13
  - r-runit=0.4.26
  - r-spatial=7.3_11
  - r-survival=2.41_3
  - readline=7.0
  - samtools=1.9
  - setuptools=44.0.0
  - simplejson=3.8.1
  - sqlite=3.28.0
  - star=2.5.2b
  - tk=8.6.10
  - trim-galore=0.4.1
  - wheel=0.34.2
  - xopen=0.7.3
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - multiqc==0.4
